# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-24 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0003_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='view_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='photod/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='upload_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
